# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is HuaLan's Blog # ex. I m chen
name: 华兰DMETAL's Blog # ex. HuaLan
email: hualandmetal@gmail.com
location: Xi'an, China # ex. Xi'an, China
company: 
company_url: 
github_url: https://github.com/hlmetal # ex. https://github.com/xxxx
github_username: hlmetal # ex. xxxx
description: A website that records my work and study experience.
favicon: favicon.ico # Image must be in assets/images
repository: hlmetal/hlmetal.github.io # ex. xxxx/xxxx.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://www.hldmetal.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: https://www-hldmetal-com.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'G-KVXT70JEK8'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, MySQL]
skill_j2ee_keywords: [Spring, Maven, MyBatis, Struct, Hibernet]
skill_web_keywords: [Vue, Element, HTML, JS, Redis, NodeJS, MongoDB]
